### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by zw81929** [vatsalsaglani/bert4rec#2]
hi,how slove this error ?

env:
cuda 12.3
Python3.10.14

Thanks 
```

../aten/src/ATen/native/cuda/Indexing.cu:1289: indexSelectLargeIndex: block: [196,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/data1/bert4rec/bert4rec-main/scripts/train.py", line 86, in <module>
    trainer(data_params=data_params,
  File "/data1/bert4rec/bert4rec-main/scripts/train_pipeline.py", line 205, in trainer
    train_loss, train_acc = train_step(model, device, train_dl,
  File "/data1/bert4rec/bert4rec-main/scripts/train_validate.py", line 47, in train_step
    output = model(source, source_mask)
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/bert4rec/bert4rec-main/scripts/bert4rec_model.py", line 51, in forward
    enc_op = self.encoder(source, source_mask)
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/bert4rec/bert4rec-main/scripts/modules.py", line 47, in forward
    self.position_encoding(self.word_embedding(source_seq)))
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data1/bert4rec/bert4rec-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/bert4rec/bert4rec-main/scripts/embeddings.py", line 31, in forward
    return x + self.pos_table[:, :x.size(1)].clone().detach()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by zw81929** [comment]
by cpu

Traceback (most recent call last):
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\bert4rec-main\scripts\train.py", line 86, in <module>
    trainer(data_params=data_params,
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\bert4rec-main\scripts\train_pipeline.py", line 205, in trainer
    train_loss, train_acc = train_step(model, device, train_dl,
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\bert4rec-main\scripts\train_validate.py", line 47, in train_step
    output = model(source, source_mask)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\bert4rec-main\scripts\bert4rec_model.py", line 51, in forward
    enc_op = self.encoder(source, source_mask)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\bert4rec-main\scripts\modules.py", line 47, in forward
    self.position_encoding(self.word_embedding(source_seq)))
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\modules\sparse.py", line 163, in forward
    return F.embedding(
  File "D:\SynologyDrive\cloud\PycharmProjects\K分位计算\.venv\lib\site-packages\torch\nn\functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by vatsalsaglani** [comment]
This might occur if your `vocab_size` is less than the amount of unique input IDs present in your data.

Suppose you have 20,000 movies or 20,000 items then your vocab size should be $20,000 + 1 = 20,001$. 

The reason for adding $1$ is we use $0$ for padding sequences so your unique items shouldn't have $0$.

I would suggest verifying this first.

If the same error comes in the `bert4rec_dataset.py` file (https://github.com/vatsalsaglani/bert4rec/blob/main/scripts/bert4rec_dataset.py#L190) then you need to verify if you are correctly calculating the length of your dataset in the `__len__` method in the Dataset class.

**Comment by zw81929** [comment]
> This might occur if your `vocab_size` is less than the amount of unique input IDs present in your data.
> 
> Suppose you have 20,000 movies or 20,000 items then your vocab size should be 20,000+1=20,001.
> 
> The reason for adding 1 is we use 0 for padding sequences so your unique items shouldn't have 0.
> 
> I would suggest verifying this first.
> 
> If the same error comes in the `bert4rec_dataset.py` file (https://github.com/vatsalsaglani/bert4rec/blob/main/scripts/bert4rec_dataset.py#L190) then you need to verify if you are correctly calculating the length of your dataset in the `__len__` method in the Dataset class.
thanks for your reply
my  data like this：
deviceId,timestamp,bondid
32152,1716220800,0
50161,1716220800,0
34793,1716220801,0
33819,1716220801,0
34385,1716220801,0
33821,1716220801,0
33866,1716220801,0
32152,1716220801,0
96657,1716220801,0
all data 
There are approximately 2 million rows of data in total,   unique deviceId  has 125327 ,so vocab_size should set 125328 ?


gpu test oom ，may be cpu test pass ，i have a10*6，how change code ？

Thank you very much for your answer
